# Similarity Matrix Demo

Copyright 2022 Bernardo C. Rodrigues

See COPYING file for license details

In [1]:
# Compute the similarity matrix using the Jaccard distance. 
from recommenders.common import get_similarity_matrix
from tests.toy_datasets import belohlavek_binary_dataset, zaki_binary_dataset, my_toy_binary_dataset

belohlavek_similarity_matrix = get_similarity_matrix(belohlavek_binary_dataset.astype(float))
my_toy_similarity_matrix = get_similarity_matrix(my_toy_binary_dataset.astype(float))
zaki_similarity_matrix = get_similarity_matrix(zaki_binary_dataset.astype(float))

print(belohlavek_similarity_matrix)
print(my_toy_similarity_matrix)
print(zaki_similarity_matrix)

2024-06-07 11:55:44,697 - recommenders - INFO - Forcing Numba compilation...
2024-06-07 11:55:45,503 - recommenders - INFO - Forcing Numba compilation OK


[[1.         0.5        0.67082039 0.70710678 0.5       ]
 [0.5        1.         0.         0.70710678 0.5       ]
 [0.67082039 0.         1.         0.31622777 0.67082039]
 [0.70710678 0.70710678 0.31622777 1.         0.70710678]
 [0.5        0.5        0.67082039 0.70710678 1.        ]]
[[1.         0.8660254  0.8660254  0.         0.         0.70710678
  0.        ]
 [0.8660254  1.         1.         0.         0.         0.81649658
  0.        ]
 [0.8660254  1.         1.         0.         0.         0.81649658
  0.        ]
 [0.         0.         0.         1.         1.         0.57735027
  0.        ]
 [0.         0.         0.         1.         1.         0.57735027
  0.        ]
 [0.70710678 0.81649658 0.81649658 0.57735027 0.57735027 1.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  1.        ]]
[[1.         0.57735027 0.8660254  0.75       0.89442719 0.57735027]
 [0.57735027 1.         0.66666667 0.8660254  0.77459667 0.66666667]
 [0.8660254 

In [ ]:
# Define a function to plot the similarity matrix
import numpy as np
import matplotlib.pyplot as plt


def plot_similarity_matrix(matrix: np.ndarray, title: str, fig: plt.Figure, ax: plt.Axes):
    subfig = ax.imshow(matrix, vmin=0, vmax=1, cmap="Greys")
    ax.set(xlabel="User", ylabel="User", title=title)
    fig.colorbar(subfig, ax=ax).set_label("Similarity")

In [ ]:
# Plot the similarity matrices
import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 3, figsize=(20, 5))
fig.suptitle("Similarity Matrices")

plot_similarity_matrix(belohlavek_similarity_matrix, "Belohlavek dataset", fig, axs[0])
plot_similarity_matrix(my_toy_similarity_matrix, "My Toy dataset", fig, axs[1])
plot_similarity_matrix(zaki_similarity_matrix, "Zaki dataset", fig, axs[2])

fig.show()